### PR TITLE
Consume go-state-types

### PR DESCRIPTION
**Pull request by ZenGround0**
@willscott opening this PR as part of a refactoring effort extracting specs-actors types to a separate repo.  Lotus depends on statediff which depends on specs actors so this is needed to complete lotus integration.  Let me know if anything looks off for example maybe I shouldn't be modifying the extern folder directly?

Currently blocked on upcoming v0.9.4 consuming go-state-types in specs actors.

FYI @Stebalien @anorth

### CODE REVIEW

**Review by willscott — APPROVED** [review]

**Comment by willscott** [comment]
let me know once unblocked and can merge + cut release

**Comment by anorth** [comment]
Actors now consumes go-state-types, but I recommend waiting for ZenGround0:update/go-state-types

**Comment by anorth** [comment]
Actually, you want https://github.com/filecoin-project/specs-actors/pull/1097

**Comment by ZenGround0** [comment]
This won't build until we update lotus.  The circular dependency with lotus makes things tricky but this branch is ready to go to consume an updated lotus (missing the statediff dep).  We'll then have to PR adding this version of statediff back as a dependency to lotus.

**Comment by willscott** [comment]
my gut feeling is it doesn't make sense to have lotus depend on this, or that this should end up in lotus shed / versioned with lotus for simplicity. thoughts @whyrusleeping?

**Pull request merged**
